// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJp6YOHWt8Y_64-xKMVMCv9GraApD6c4k',
    appId: '1:812064294731:android:468b2dc53a3cb2fecd4ace',
    messagingSenderId: '812064294731',
    projectId: 'hungryhands-69809',
    databaseURL: 'https://hungryhands-69809-default-rtdb.firebaseio.com',
    storageBucket: 'hungryhands-69809.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuxiVSNSme6YMenu9b5TJyFLBhwcLLuRI',
    appId: '1:812064294731:ios:eeaae0b2c25e941acd4ace',
    messagingSenderId: '812064294731',
    projectId: 'hungryhands-69809',
    databaseURL: 'https://hungryhands-69809-default-rtdb.firebaseio.com',
    storageBucket: 'hungryhands-69809.appspot.com',
    androidClientId: '812064294731-1n64chlrp85e57ovkqvefo2kigp86c2n.apps.googleusercontent.com',
    iosClientId: '812064294731-d77em2smq3h2dprsma6au83kt55n5hsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.hungryHandsDriver',
  );
}
